### ISSUE TITLE
More info for RISK-V

### ISSUE THREAD

**Issue by masterct88** [jacobbar/fruity-pikvm#1]
Hi, 
i want to know if this repository will allow pikvm to work on RISK-V architecture, like mangoPi, and if something need to be done before installing it.
Thanks!

**Comment by jacobbar** [comment]
at the moment there is no support for RISK-V architecture as I don't have an SBC to test it with, if you have and want to test it send me a message on discord username jacobb#1987

**Comment by masterct88** [comment]
Sorry to bother you @jacobbar, i cant add you on discord. 
Please, add me: "Giorno Giovanna#6278"
