### ISSUE TITLE
ISO mount support

### ISSUE THREAD

**Issue by masterlog80** [jacobbar/fruity-pikvm#12]
Hello,

By modifying the script here, I was able to have this working on Orange Pi Zero 3 smoothly, by using the official Image `Orangepizero3_1.0.2_ubuntu_jammy_server_linux6.1.31.img` [1] (of course it may work with other Debian based image, but this has Python 3.10 already installed so it's easier to setup). Checking KVMD version it shows `3.198` which can eventually be pretty old.
I am assuming this is the reason of the lack of ISO mount support:
![current status](https://github.com/jacobbar/fruity-pikvm/assets/33828929/46af0bb3-b977-4307-aa5c-f0f726c873a7)
At least comparing to the screenshots online:
![desired status](https://github.com/jacobbar/fruity-pikvm/assets/33828929/98efe1a3-aacd-4de9-9e77-f9c3627e665f)
Is there someone able to have the ISO mount working? Or to eventually upgrade it to a more recent [version](https://github.com/pikvm/kvmd/releases)?

Thanks and regards,

[1] http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi-Zero-3.html

**Comment by halida** [comment]
Same issue here. Also is there any way to check deb package source code? Thanks project only have install.sh.

**Comment by masterlog80** [comment]
@halida We may need assistance from the person who created this repo (@jacobbar), but it doesn't seem there is a lot of activity recently....

**Comment by leux0** [comment]
![{3C4560EF-942E-4659-B003-997D7589933E}](https://github.com/user-attachments/assets/17b05758-4986-410c-9cc0-95a8b52ee1ff)

**Comment by masterlog80** [comment]
Hello @leux0 , sorry but can you please explain your [update](https://github.com/jacobbar/fruity-pikvm/issues/12#issuecomment-2232375922) above?

**Comment by YipKo** [comment]
@masterlog80 
I've tested it and it works well on my Orange Pi Zero 3 with the official system image `Orangepizero3_1.0.2_ubuntu_jammy_server_linux6.1.31`.

Here are details:

1. Applying patches requires mounting a partition (ext4 file system) for ISO mount  functionality. 

- For example, you can use **gparted** or **diskgenius** to repartition the SD card and create a new partition using the remaining space on the SD card. 

- Or, you can use **manually created img file** for mounting it as partitions
  ```
  dd if=/dev/zero of=/root/disk.img bs=1M count=8192 status=progress
  mkfs.ext4 /root/disk.img
  
  ```
2. Use `lsblk` to view storage device information, assuming the new partition is `/dev/mmcblk0p2` (if you use USB flash drive, it should be like `/dev/sda1`. Or, if you use img file as partitions, it would be `/root/disk.img`)

    <img width="553" alt="image" src="https://github.com/user-attachments/assets/15099fb8-ac60-424d-99d4-663c7fc21830">

3. Add the `/dev/mmcblk0p2` partition mount entry to the last line of `/etc/fstab` :
 `/dev/mmcblk0p2 /var/lib/kvmd/msd ext4 nodev,nosuid,noexec,rw,errors=remount-ro,data=journal,X-kvmd.otgmsd-root=/var/lib/kvmd/msd,X-kvmd.otgmsd-user=kvmd 0 0`

4. Edit `/etc/kvmd/override.yaml` and change the msd type option from `disabled` to `otg` 
    ```
    kvmd:
        msd:
            type: otg
    ```
 
6. reboot system
 `sudo reboot`

**Comment by masterlog80** [comment]
@YipKo thank you for your update.
I will check that asap, but does it apply on the UI as well? 
Like adding the "Drive" menu which I have seen on the official device:
![image](https://github.com/user-attachments/assets/060abd99-a4fb-4c0a-a05d-975794e52997)

Regards,

**Comment by YipKo** [comment]
@masterlog80 It does apply on the UI and works perfectly. Just follow the instructions above.  :)

**Comment by masterlog80** [comment]
It seems working thanks! 
But I need to try with a real ISO.

**Comment by masterlog80** [comment]
It works perfectly @YipKo, thank you for your assistance!
